### ISSUE TITLE
Setting denom with non-primary but registered nick doesn't work

### ISSUE THREAD

**Issue by mspoon** [josephdunn/willie-modules#40]
I have registered a secondary nick to my account. I am authed to services. I can set my denomination with my primary nick, but I cannot set with my secondary nick. I get the 'you need to be authed to services' message.

**Comment by aletheist** [comment]
This has been fixed. @josephdunn, this issue can be closed.

**Comment by aletheist** [comment]
This needs to be reopened. Users have promptly discovered how to circumvent and steal even the account nick from someone. I propose a new strategy.

* Users will need to `/nick` to their account name/nick in order to use `.setdenom`
* Lookups will executed against a user's account, not their nick.
* Users must be logged it to be `.denom`ed

If anyone can think of a way to set aliases so we can have offline denom checking I'm all ears.

**Comment by aletheist** [comment]
I've opened up PR #48 to address this new problem. It only allows users to .denom users that are in the channel. I have not come up with a strategy that effectively prevents nick stealing otherwise.
